### ISSUE TITLE
Server tries to load all files in the folder as a plugin and fails to start

### ISSUE THREAD

**Issue by akira28** [Kong/kong-js-pdk#151]
I'm trying to upgrade to the latest version 0.5.3 but I'm facing this issue.
I have a bunch of files like `.nyc_output` `.gitignore` and some tests, but when I try to start Kong it now errors out with this error:
`Error: Cannot find module '/usr/local/kong/plugins/.nyc_output'`
I tried eliminating some of these files, but for example it then tries to load the __tests__ folder as a plugin :(
`Error: Cannot find module '/usr/local/kong/plugins/__tests__'`

I'm launching the server with these two configs:

```
pluginserver_js_start_cmd = /usr/local/kong/plugins/node_modules/kong-pdk/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/plugins

pluginserver_js_query_cmd = /usr/local/kong/plugins/node_modules/kong-pdk/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/plugins --dump-all-plugins
```

What should I do to fix this?

It worked correctly on version 0.4.4

**Comment by douggsky** [comment]
A workaround for this issue is to keep your implementation separate and just create a symlink for each plugin in the pdk plugins directory:

```
/usr/local/kong/plugins/impl/
- /myplugin1
 - node_modules/
 - package.json
 - plugin.js
- /myplugin2
 - node_modules/
 - package.json
 - plugin.js
- ... 
```

```
/usr/local/kong/plugins/link/
- myplugin1.js -> ../impl/myplugin1/plugin.js
- myplugin2.js -> ../impl/myplugin2/plugin.js
- ...
```


From `/usr/local/kong/plugins/link/` create the symlinks:

```
ln -s ../impl/myplugin1/plugin.js myplugin1.js
ln -s ../impl/myplugin2/plugin.js myplugin2.js
...
```


You can script all this with something like the following:

```
for d in /usr/local/kong/plugins/impl/*/; do \
  cd $d && test -r package.json && npm install --ci && \
  cd /usr/local/kong/plugins/link/ && ln -s ../impl/$(basename $d)/plugin.js $(basename $d).js; \
done
```


Then modify the plugins-directory:

```
pluginserver_js_start_cmd = /usr/local/kong/plugins/node_modules/kong-pdk/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/plugins/link/
pluginserver_js_query_cmd = /usr/local/kong/plugins/node_modules/kong-pdk/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/plugins/link/ --dump-all-plugins
```

**Comment by akira28** [comment]
@douggsky thanks for the response. In the end we decided to migrate all our plugins to Golang, as it seems to be better maintained and it's faster anyway. I think you should add this workaround to the docs, and close this ticket :)

**Comment by hanshuebner** [comment]
Tracking a documentation update in internal ticket KAG-2604, closing this issue.
